husjon/obsidian-file-cleaner-redux

- src/util.ts
Fixes build of inUseAttachments array.
In cases were a markdown file had more than one attachment, these were not added due to the use of pop.
> fixed buildup of inUseAttachments

- src/util.ts
Currently canvas files are currently not indexed by Obsidian, this results in attachment being unintentionally removed during cleanup.
This PR fixes this by going through each canvas file fetching the nodes and builds an array of the included attachments.
This array is then used to ignore these files when running the cleanup.
> Feature: Add support for canvas

- src/locales/en.ts
- src/locales/locale.d.ts
- src/settings.ts
- src/util.ts
This PR allows empty markdown files containing **only** specific frontmatter tags to be added to the list of files to be removed.
Fixed #16
> Add: Support for cleaning files with only frontmatter

- src/util.ts
Replaced usage of `getFiles` in addition to `getAllLoadedFiles` with only `getAllLoadedFiles`.
`getAllLoadedFiles` already gets everything.
> Fix: Simplified file and folder lookup

- src/locales/en.ts
- src/locales/locale.d.ts
- src/settings.ts
- src/util.ts
- updated settings strings
- added toggle for using exclusion or inclusion of folders
- updated settings interface to allow for includeFolders
- updated setting for excluded folders with new labels and descriptions
- made excludeInclude an enum to make it easier to read
- updated final filter to use excluded/included folders
Fixes #25
> Add: Exclude / Include folders toggle

- src/util.ts
When using wildcard extensions (`.*`) or `.canvas` in the **Attachment extensions** option, canvas files where not properly checked for size.
This PR checks for the canvas files size to determine if any nodes are added.
Comment from filter:
```
// Newly created or cleared out canvas files are currently 28bytes or less
// A single node adds at a minumum about 80 bytes,
//   hence any canvas file less than 50 bytes are tagged as candidates for cleanup
```
```json
{}
```
Empty (after deleting nodes):
```json
{
"nodes":[],
"edges":[]
}
```
(minified, this is 24 bytes)
Fixes #46
> Added check for canvas files when wildcard (`.*`) or `.canvas` extension is used

- README.md
- src/helpers/extras/excalidraw.ts
- src/helpers/helpers.ts
- src/helpers/markdown.ts
- src/util.ts
Adds support for Excalidraw files
Current implementation requires that the compression is disabled in teh Excalidraw Settings.  
`Obsidian Settings > Community plugins > Excalidraw > Saving > Compress Excalidraw JSON in Markdown`
- **added initial checkExcalidraw helper function**
- **added helper function to get the sections from a markdown file**
- **extended checkExcalidraw to parse the json object and delete the file if it has no elements**
- **extracted plugin check to helpers**
- **check if user has excalidraw installed before checking files**
> Add support for Excalidraw

- src/locales/en.ts
- src/locales/locale.d.ts
- src/settings.ts
- src/util.ts
Adds support for cleaning up the Obsidians `.trash` folder based on an age threshold.
Changes:
- **added property FileCleanerSettings.obsidianTrashCleanupAge**
- **added labels**
- **added setting for setting "Trash directory age treshold"**
- **added function to check the users `.trash` folder and clean up files above a certain age threshold**
- **added some log messages**
- **only run cleanTrashFolder when Obsidian Trash is used**
> Automatically delete trash files older than X days

- README.md
- src/helpers/extras/excalidraw.ts
- src/helpers/helpers.ts
- src/helpers/markdown.ts
- src/util.ts
Excalidraw support was originally added in #66 as part of version 1.1.0, it did however have issues and was disabled in version 1.1.1.
Current implementation requires that JSON compression is disabled in Excalidraw Settings.  
`Obsidian Settings > Community plugins > Excalidraw > Saving > Compress Excalidraw JSON in Markdown`
Changes:
* Add Excalidraw support again
* added initial checkExcalidraw helper function
* added helper function to get the sections from a markdown file
* extended checkExcalidraw to parse the json object and delete the file if it has no elements
* extracted plugin check to helpers
* check if user has excalidraw installed before checking files
* added check for backlinks, skip the file if there are any
* formatting
* get the backlink keys directly, instead of casting …
> Re-add Excalidraw support

- src/helpers/markdown.ts
- src/locales/en.ts
- src/locales/locale.d.ts
- src/settings.ts
- **chore(FileCleanerSettings): added boolean to ignore all frontmatter**
- **chore(i18n/en): added label and description**
- **chore(Settings): added entry for "Ignore all frontmatter"**
- **chore(Settings): disable the "Ignored frontmatter" input when all frontmatter is ignored**
- **chore(checkMarkdown): return true instantly when ignoreAllFrontmatter is enabled**
Settings
While **Ignore all frontmatter** is enabled, all **empty** files are now tagged for cleanup.
> Add feature: Ignore all frontmatter

- src/locales/en.ts
- **chore(locales/en): added description about regular expression support**
- **chore(locales/en): expanded description for excluded folder to make it a bit more clear**
> 79 trying to use a wildcard in include exclude folder list doesnt work and produces an error 1

- src/helpers/canvas.ts
Extended canvas card parser to support Markdown style (`![](path/to/file)`) in addition to Wikilinks style (`![[path/to/file]]`).
It now also supports "Shortest path when possible" (which is the default in Obsidian)
Fixes #31
> Fix: Canvas card attachments link style + shortest path support

- src/helpers/canvas.ts
Markdown-style attachment links uses url encoding meaning spaces are replaced with `%20`.
This caused the lookup to look for filenames with literally `%20` in the name if it used spaces.
This PR also makes it so that filenames can have parenthesis in the filename.
> Fix Markdown-style attachment link parsing in canvas nodes.

- src/helpers/canvas.ts
If using a templates which builds on the attachment syntax (prefixed with Wikilink-style `[[` and `![[` or Markdown-style `![`), this can make the regular expression match these blobs.
When the match is passed on to Obsidians getFirstLinkpathDest it returns undefined.
These undefined matches are now filtered out.
> fix(getCanvasAttachments): filter out falsely matched attachments

- src/helpers/canvas.ts
Since `getFirstLinkpathDest` returns null for non-existing files, we need to check if we do have a TFile object prior to accessing `.path`
Fixes #93 (notification issue)
> fix(getCanvasCardAttachments): return only if the FileLink exist

- src/helpers/codeblock.ts
Replaced `matchAll` with `match` as `matchAll` returns an iterator which would be truthy.
> fix(parseCodeblock): now aborts if the codeblock is invalid

- src/helpers/codeblock.ts
Codeblocks do not strictly need the ending fence to be valid.
If the ending fence is there, we strip it off.
> fix(parseCodeblock): only check for codeblock fence in the beginning of the codeblock

- package.json
- pnpm-lock.yaml
- src/locales/en.ts
- src/modals/DeletionConfirmationModal.ts
- src/modals/DeletionConfirmationModalComponent.svelte
- src/util.ts
This PR adds support for manually selecting which files to keep during the final preview window.
A quick video showing it in action can be found here https://youtu.be/AKdEAosHkf8
> Add checkbox for preview of deleted files

- README.md
- src/util.ts
This PR adds support for the Meld Encrypt Plugin
It makes it so that if the user has the plugin installed, any mdenc files will be omitted from the cleanup sequence.
- **feat(checkFile): added explicit support for Meld Encrypt**
- **chore(README): added entry about Meld Encrypt**
> Add support for Meld Encrypt

- src/modals/DeletionConfirmationModalComponent.svelte
This PR makes it so that "Select all" and "Unselect all" now uses icons on mobile devices.
| old | new |
|  -  |  -  |
| <img width="350" alt="Image" src="https://github.com/user-attachments/assets/1ac24089-1925-406b-ba4c-64c4ae2faf61" /> | <img width="350" alt="app___obsidian md_index html(iPhone SE)" src="https://github.com/user-attachments/assets/7689c44a-e7e1-4643-b7bc-984f2c5eac00" /> |
> Fix: "Select all" and "Unselect all" now uses icons on mobile

- src/helpers/helpers.ts
- src/index.ts
- src/locales/en.ts
- src/locales/locale.d.ts
- src/settings.ts
- src/util.ts
This PR adds an option to clean up empty markdown files when its respective tab is closed (default to **off**).
> Add: cleanup of empty files when closed

- src/index.ts
- src/util.ts
Since the file-close cleanup runs without all the extra vault scanning, the folder inclusion/exclusion check was not run.
This is now added as part of this procedure.
> Fix: Added missing check for folder inclusion/exclusion for file-close cleanup
